server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JAlayon/spring-cloud-config-server-repository
          default-label: main
          username: JAlayon
          password: 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
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: springCloudPassword!
logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG
